name: TaML
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - matplotlib>=3.5
  - notebook
  - numpy
  - pandas
  - scikit-learn>=1.0
  - scipy
  - seaborn
  - tensorflow==2.8.0
